server:
  port: 9998
spring:
  application:
    name: eureka-client-hi
eureka:
  instance:
      lease-expiration-duration-in-seconds: 30 #多久没有上报心跳就移除自己(S)
      lease-renewal-interval-in-seconds: 12  #心跳间隔时间(S)
  client:
    service-url:
      defaultZone: http://192.168.22.36:8761/eureka/
