server:
  port: 9001

  # hostname 设置当前实例的主机名称
  #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
  #当只有自己一台注册中心时  可以不设置注册地址

eureka:
  instance:
    hostname: www.springcloudTest.com
    prefer-ip-address: false
  client:
    register-with-eureka: true
    #多节点时 true
    fetch-registry: true
    service-url:
      defaultZone: http://www.springcloudTest2.com:8761/eureka/,http://www.springcloudTL.com:9000/eureka/
  server:
    enable-self-preservation: false #enable-self-preservation: false 关闭自我保护模式
    eviction-interval-timer-in-ms: 1000 # 续期时间，即扫描失效服务的间隔时间(毫秒)
spring:
  application:
    name: eureka-center
  cloud:
    inetutils:
      timeout-seconds: 10
